### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Yu Tian",
    "email": "yu@acme.org",
    "password": "123456"
}

### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Alice Tian",
    "email": "alice@acme.org",
    "password": "123456"
}

### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Bob Hua",
    "email": "bob@acme.org",
    "password": "123456"
}

### signin user (invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "tian@acme.org",
    "password": "a123456"
}


### signin user (valid)
# @name signin

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "yu@acme.org",
    "password": "123456"
}

@token = {{ signin.response.body.token }}


### signin user (valid)

# @name signinone
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "bob@acme.org",
    "password": "123456"
}

@token1 = {{ signinone.response.body.token }}



### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "project X",
    "members": [1, 2],
    "public": false
}

### create direct chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "members": [1, 2],
    "public": false
}

### create chats without me
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token1}}

{
    "name": "project Y",
    "members": [2, 3],
    "public": false
}

### create direct chat without me
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token1}}

{
    "members": [2, 3],
    "public": false
}

### get chat list

GET http://localhost:6688/api/chats
Authorization: Bearer {{ token }}

### delete chat

DELETE http://localhost:6688/api/chats/1
Authorization: Bearer {{ token }}


### get user list

GET http://localhost:6688/api/users
Authorization: Bearer {{ token }}

### upload file

POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="xdiff1.png"
Content-Type: application/octet-stream

< /Users/jason/snapshots/xdiff1.png
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--

### get files

GET http://localhost:6688/api/files/1/3fb/bc2/2d01ebcd32fda61adb8e48c09111bef621.png
Authorization: Bearer {{ token }}


### send a message

POST http://localhost:6688/api/chats/1
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "content": "Hello, World!",
    "files": []
}

### get messages

GET http://localhost:6688/api/chats/1/messages?limit=6&last_id=5
Authorization: Bearer {{ token }}
